### ISSUE TITLE
EIS Links to Projects aren't forwarded and projects don't exists in the SDA pages

### ISSUE THREAD

**Issue by np00** [SmartDataAnalytics/sda.tech#13] opened 2018-04-12 09:37 UTC
Fabrizio: Examples are "ODINE", ...

**Comment by np00** [comment] 2018-04-12 09:40
You can create it yourself in RDF:  (example project description) 
https://github.com/SmartDataAnalytics/sda.tech/blob/develop/rdf-data/sda.tech.ttl#L1600

**Comment by np00** [comment] 2018-04-12 09:41
Maybe history of old project is findable via Google Cache

**Comment by badmotor** [comment] 2018-04-12 15:41
On the Web Archive it is still possible to retrieve those old pages, see e.g.: https://web.archive.org/web/20170524183341/http://eis.iai.uni-bonn.de/Projects.html

**Comment by badmotor** [comment] 2018-04-12 15:44
@RohanAsmat for now we put your name here, but it might be a good idea as well to reassign the full complete porting of the old EIS pages to e.g. a student assistant.

**Comment by RohanAsmat** [comment] 2018-04-12 15:56
Actually I understand the projects are missing, which can be added but can you give an example interaction where projects aren't forwarded.

**Comment by RohanAsmat** [comment] 2018-04-12 15:58
I think the projects aren't meant to be further forwarded once we display their whole information, but maybe what you mean is that the URL's to the project home pages are not right?

**Comment by badmotor** [comment] 2018-04-12 16:17
The current behaviour, if you go e.g. to an old EIS link like http://eis.iai.uni-bonn.de/Projects/Linda.html, is to redirect to http://sda.cs.uni-bonn.de/Projects/Linda.html .
Which is fine as long as the page about the Linda project exists at http://sda.cs.uni-bonn.de/Projects/Linda.html . So if we can just re-create the page about the Linda project at that new sda address, then the problem is solved. 

Another interesting feature for the SDA website would be to categorise all projects that have ended as "Past Projects", similarly to the categories currently at http://sda.tech/project/ (e.g. "Funded Projects"), so that all those old projects from EIS would still be available on the website but kind of grouped and "hidden" under that category. But that's another additional item to be discussed... :)

**Closed** 2018-06-26 16:19 UTC
Labels: Projects, bug, enhancement, rdf
